#!/system/bin/sh
# call userinit.sh if present in /data/local

if [ -e /data/local/userinit.sh ];
then
   log -p i -t userinit "Executing /data/local/userinit.sh";
   /system/bin/sh /data/local/userinit.sh;
   setprop vu.userinit.active 1;
fi;

rm -f /data/data/com.android.providers.telephony/databases/telephony.db
rm -f /data/data/com.android.providers.telephony/databases/telephony.db-journal
busybox rm -f /data/data/com.android.providers.telephony/databases/telephony.db
busybox rm -f /data/data/com.android.providers.telephony/databases/telephony.db-journal
